project_id = "vxizwhmqvmfoplthjdvu"

[functions.ai-project-assistant]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.cnpj-lookup]
verify_jwt = true

[functions.cep-lookup]
verify_jwt = true

[functions.send-welcome-notification]
verify_jwt = true